# Generated by Django 6.0.6 on 2026-06-26 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0012_delete_contact_contactmessage_subject_excelfile_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("name", models.CharField(default="Wearable", max_length=120)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("firmware", models.CharField(blank=True, max_length=50)),
                ("battery", models.IntegerField(blank=True, null=True)),
                ("current_session", models.CharField(blank=True, max_length=200)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "device_id")},
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("signup", "Signup"), ("login", "Login 2FA")],
                        max_length=10,
                    ),
                ),
                ("code_hash", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "purpose"], name="login_email_email_83ce04_idx"
                    )
                ],
            },
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
