# Generated by Django 6.0.6 on 2026-06-26 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0013_device_emailotp_delete_otp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("HR", "Heart Rate (bpm)"),
                            ("EDA", "Skin Conductance (µS)"),
                            ("TEMP", "Skin Temperature (°C)"),
                            ("ACC", "Movement Magnitude (g)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[("gt", "Greater than"), ("lt", "Less than")],
                        max_length=2,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("label", models.CharField(blank=True, max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=150)),
                ("session", models.CharField(max_length=200)),
                ("offset_sec", models.FloatField()),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["offset_sec"],
                "indexes": [
                    models.Index(
                        fields=["owner", "session"], name="login_sessi_owner_d2d3fc_idx"
                    )
                ],
            },
        ),
    ]
