# Generated by Django 6.0.6 on 2026-06-26 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0014_sessionannotation_alertrule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertFired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal", models.CharField(max_length=10)),
                ("label", models.CharField(max_length=120)),
                ("operator", models.CharField(max_length=2)),
                ("threshold", models.FloatField()),
                ("actual_mean", models.FloatField()),
                ("owner", models.CharField(max_length=150)),
                ("session", models.CharField(max_length=200)),
                ("fired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firings",
                        to="login.alertrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_fired",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fired_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-fired_at"],
                        name="login_alert_user_id_4856b0_idx",
                    )
                ],
            },
        ),
    ]
