# Generated by Django 5.2.16 on 2026-07-15 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alertfired'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('medication', 'Medication List'), ('imaging', 'Imaging / Scan'), ('sensor_data', 'Sensor / Device Data'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'doc_type'], name='login_uploa_user_id_d6ef83_idx')],
                'unique_together': {('user', 'filename')},
            },
        ),
    ]
