# Generated by Django 5.2.16 on 2026-07-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRVAnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('session', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('watch', 'Watch'), ('alert', 'Alert')], max_length=10)),
                ('score', models.FloatField()),
                ('reasons', models.TextField(blank=True)),
                ('model_status', models.CharField(blank=True, max_length=20)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrv_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_hrvan_user_id_135663_idx')],
            },
        ),
    ]
