[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://103.25.231.107:8000/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"
